<Button>: #parent tag for buttons, meaning that every button tag will have these properties
    font_size: 20
    color: 0.11, 0.13, 0.21, 1
    size_hint: 0.1, 0.1

<FloatLayout>:
    Button:
        pos_hint: {"x": 0.5, "top": 1} # "x", "y", "top", "bottom", "left", "right"
        text: "test"
    Button:
        id: angela
        pos_hint: {"y":0.3}
        text: "Michael"
        background_color: 0.03, 0.04 , 0.04 , 1
